### ISSUE TITLE
JSON Content-Type with charset isn't universal

### ISSUE THREAD

**Issue by cgrayson** [activeprospect/leadconduit-integration-custom#12]
The JSON delivery sets `Content-Type` to `application/json; charset=utf-8`, but some recipients – as Tim found when trying to integrate with SignalFx – want just `application/json` with no `charset`. 

Though there's already a facility to map header values, this integration will skip the delivery attempt (!) if the user specifies a `Content-Type` themselves.

**Comment by alexkwolfe** [comment]
I think it probably makes sense to allow the user to override the Content-Type header provided the media type is some variant of JSON (i.e. application/json, application/vnd.foo+json, application/json; charset=utf-8, etc).

We may also consider removing charset=utf-8 as the default.

**Comment by cgrayson** [comment]
I don't know whether a better default is to have it (like [Twilio requires](https://github.com/activeprospect/leadconduit-integration-twilio/pull/3/commits/c16f90ddf1897d6368deb939a99ced1c23edc2f4)), or to not have it (like SignalFx requires). But it does seem like either way, we need to allow overriding it. 

Sounds like you want to validate that setting. Should it only be for JSON types, though? The `application/x-www-form-urlencoded` also specifies `charset`, and validation code is common.

**Comment by dr-strangecode** [comment]
Is this something we're likely to get?  It would allow talking with SignalFX and could be handy.

**Comment by alexkwolfe** [comment]
Yes. This is an easy change. It just hasn't been made yet. Though, I don't think any of our customers will use SignalFX.
