### ISSUE TITLE
Support additional parameters in xml integration when xml_parameter is used

### ISSUE THREAD

**Issue by aggroskater** [activeprospect/leadconduit-integration-custom#26]
Howdy. The new xml integration is awesome! It should make integrating with Zoho straightforward. The only missing feature --for Zoho integration at least-- is the ability to specify additional parameters in addition to `xml_parameter`. Below is a patch to add this feature (though truthfully, I don't know whether you'd want to put it here or include it in the custom form integration instead). Full disclosure, this is my very first foray into coffeescript.

http://pastebin.com/raw/tJV5Ce9X

**Comment by cgrayson** [comment]
Hey Preston, thanks for that. I didn't see your patch until late today (github doesn't notify on issue edits). I made a PR from it; the only thing I changed was the extra parameter name (`extra_parameter.*`, over `parameter.*`, to try to emphasize that it's optional). We haven't talked about this internally (e.g., whether it should go here or in `form`), but we should get to it by tomorrow. Thanks!

**Comment by cgrayson** [comment]
FYI - this has been completed and deployed to staging and production (version `2.7.0`).
