### ISSUE TITLE
Form POST: HTTP 200 response with empty body is a failure

### ISSUE THREAD

**Issue by alexkwolfe** [activeprospect/leadconduit-integration-custom#30]
When the Outcome on match and search term are unspecified, the default "success" outcome should be returned.

**Comment by alexj** [comment]
Jonathan, is this something you could knock out today?

**Comment by jgrayson676** [comment]
Sure

**Comment by cgrayson** [comment]
Deployed as `2.7.2` /cc @mrjuicebox
