### ISSUE TITLE
Add ability to translate UTF-8 to ASCII 

### ISSUE THREAD

**Issue by alexj** [activeprospect/leadconduit-integration-custom#33]
We’re running into issues where an external legacy system can’t accept accented characters. Can we update this integration to translate UTF-8 to ASCII? Perhaps using a library like https://github.com/FGRibreau/node-unidecode

This would be an option that the flow creator could enable. It would be off by default.

**Comment by cgrayson** [comment]
See [this ticket](https://activeprospect.zendesk.com/agent/tickets/10246).
