### ISSUE TITLE
Support stuffing JSON into an HTTP parameter

### ISSUE THREAD

**Issue by alexkwolfe** [activeprospect/leadconduit-integration-custom#51]
Normally the JSON integration sends a blob of JSON in the HTTP request body with a Content-Type of application/json. 

Sometimes we want to stuff that JSON blob in a parameter in the HTTP request body with a Content-Type of application/x-www-form-urlencoded. This is supported in the XML integration by the `xml_parameter` request variable.

Here's a sample from production:

![screen shot 2017-01-27 at 1 13 07 pm](https://cloud.githubusercontent.com/assets/569/22384297/54f0ac1c-e493-11e6-934b-dd7f3e42cd57.png)

**Comment by aggroskater** [comment]
Pretty sure this is already implemented for xml and json (along with extra parameters) here:

https://github.com/activeprospect/leadconduit-integration-custom/pull/29

**Comment by cgrayson** [comment]
First from #28, tidied a little in #29 😃 but yep, you're right, @aggroskater. Thanks!
